CREATE TABLE accounts (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, vault_key VARCHAR(32) NOT NULL, handle VARCHAR(16) NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(120) NOT NULL, memex_name VARCHAR(120) NOT NULL, tier VARCHAR(16) DEFAULT 'default' NOT NULL, created_at DATETIME NOT NULL, last_seen_at DATETIME DEFAULT NULL, suspended_at DATETIME DEFAULT NULL);
CREATE UNIQUE INDEX UNIQ_CAC89EAC527A1539 ON accounts (vault_key);
CREATE UNIQUE INDEX UNIQ_CAC89EAC918020D9 ON accounts (handle);
CREATE UNIQUE INDEX UNIQ_CAC89EACE7927C74 ON accounts (email);
CREATE TABLE identities (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ref VARCHAR(16) NOT NULL, provider VARCHAR(32) NOT NULL, subject VARCHAR(191) NOT NULL, email VARCHAR(180) DEFAULT NULL, created_at DATETIME NOT NULL, last_used_at DATETIME DEFAULT NULL, account_id INTEGER NOT NULL, CONSTRAINT FK_FA392CE89B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX idx_identities_account ON identities (account_id);
CREATE UNIQUE INDEX UNIQ_FA392CE8146F3EA3 ON identities (ref);
CREATE UNIQUE INDEX uniq_identity_provider_subject ON identities (provider, subject);
CREATE TABLE user_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ref VARCHAR(16) NOT NULL, account_id INTEGER NOT NULL, session_key VARCHAR(64) NOT NULL, php_session_id VARCHAR(128) DEFAULT NULL, created_at DATETIME NOT NULL, last_seen_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, created_ip VARCHAR(45) DEFAULT NULL, last_ip VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(512) DEFAULT NULL, CONSTRAINT fk_user_sessions_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE);
CREATE UNIQUE INDEX uniq_user_sessions_key ON user_sessions (session_key);
CREATE UNIQUE INDEX uniq_user_sessions_ref ON user_sessions (ref);
CREATE INDEX idx_user_sessions_account ON user_sessions (account_id);
CREATE INDEX idx_user_sessions_expires ON user_sessions (expires_at);
CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL PRIMARY KEY, sess_data BLOB NOT NULL, sess_lifetime INTEGER NOT NULL, sess_time INTEGER NOT NULL);
CREATE INDEX idx_sessions_lifetime ON sessions (sess_lifetime);
CREATE TABLE oauth_clients (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, client_id VARCHAR(64) NOT NULL, client_name VARCHAR(255) NOT NULL, redirect_uris CLOB NOT NULL, created_at DATETIME NOT NULL, last_used_at DATETIME DEFAULT NULL);
CREATE UNIQUE INDEX uniq_oauth_clients_client_id ON oauth_clients (client_id);
CREATE INDEX idx_oauth_clients_unused ON oauth_clients (created_at) WHERE last_used_at IS NULL;
CREATE TABLE oauth_codes (code VARCHAR(64) NOT NULL PRIMARY KEY, client_id VARCHAR(64) NOT NULL, account_id INTEGER NOT NULL, redirect_uri CLOB NOT NULL, code_challenge VARCHAR(128) NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME NOT NULL, CONSTRAINT fk_oauth_codes_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE);
CREATE TABLE bearer_tokens (token_hash VARCHAR(64) NOT NULL PRIMARY KEY, account_id INTEGER NOT NULL, connection_id INTEGER NOT NULL, created_at DATETIME NOT NULL, CONSTRAINT fk_bearer_tokens_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE);
CREATE UNIQUE INDEX uniq_bearer_tokens_connection ON bearer_tokens (account_id, connection_id);
